# Generated by Django 4.0.6 on 2022-08-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainprojectapp', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
